packages:
  go:
  - url: github.com/tommyknows/packa
    version: 0.1.0
  brew:
    - name: vim
settings:
  handler:
    go:
      printCommandOutput: true
      updateDependencies: false
      workingDir: ~/.packa
    brew:
      taps:
        - "homebrew/cask"
      updateOnInit: true
